thu-info-community/thu-info-app

src/network/water.ts
src/ui/home/water.tsx

清紫源泉api改变，不再要求电话，而改为联系人微信昵称，由其api提供。
不再要求订水api不要求的字段非空。

Fix water ordering api and ui.

---

src/ui/settings/settings.tsx

I really just want to add a scroll view, but pre-commit gave me many errors so I end up fixing those all.

Added a scroll view for settings page

---

src/ui/schedule/scheduleAdd.tsx

Clear button for adding course --> choose course time page

---

src/ui/home/washerWeb.tsx

Partially: #286 
Work-in-progress.

Washer web color

---

src/ui/home/crCoursePlan.tsx
src/ui/home/electricity.tsx
src/ui/home/form.tsx
src/ui/home/gitlabSearch.tsx
src/ui/home/reservesLibWelcome.tsx
src/ui/home/sportsSelect.tsx
src/ui/home/water.tsx
src/ui/schedule/scheduleAdd.tsx
src/ui/settings/feedback.tsx

All placeholder color change & switched to fontB3

---

src/ui/news/newsDetail.tsx

<pre>亮                                                      暗                                              原始</pre>

Added color override - Draft

---

src/ui/news/newsDetail.tsx

发现当网页加载较慢时WebView依然是白的。于是在WebView的style里面添加了默认背景。另外用*选择器以免鬼畜

Modified color override

---

src/ui/schedule/schedule.tsx

Fixing a bug
Also moved the date display to the scrolling list.

Used FlatList to scroll more nicely

---

.github/workflows/pr-check.yml

chore: improve PR workflow

---

src/assets/icons/IconBook.tsx
src/assets/icons/IconCheck.tsx
src/assets/icons/IconCheckGrey.tsx
src/assets/icons/IconConfig.tsx
src/assets/icons/IconDorm.tsx
src/assets/icons/IconDormScore.tsx
src/assets/icons/IconDown.tsx
src/assets/icons/IconDownload.tsx
src/assets/icons/IconEvaluation.tsx
src/assets/icons/IconExchange.tsx
src/assets/icons/IconExclamation.tsx
src/assets/icons/IconGitLab.tsx
src/assets/icons/IconHistory.tsx
src/assets/icons/IconHomeTab.tsx
src/assets/icons/IconLeft.tsx
src/assets/icons/IconLibRoom.tsx
src/assets/icons/IconLocal.tsx
src/assets/icons/IconLock.tsx
src/assets/icons/IconPerson.tsx
src/assets/icons/IconPhysicalExam.tsx
src/assets/icons/IconReserve.tsx
src/assets/icons/IconRight.tsx
src/assets/icons/IconSettingsTab.tsx
src/assets/icons/IconSocket.tsx
src/assets/icons/IconSubscription.tsx
src/assets/icons/IconSubscriptionLogo.tsx
src/assets/icons/IconWasher.tsx

Some icons have a %1 white background. This PR removes it.

fix: Removed icon backgrounds

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/components/Root.tsx
apps/thu-info-app/src/redux/slices/config.ts
apps/thu-info-app/src/ui/home/dorm.tsx
apps/thu-info-app/src/ui/home/home.tsx
apps/thu-info-app/src/ui/home/washer.tsx

Fixes #442 
需要研究一下 redux 的使用是否正确。

feat: Washer screen new UI

---

apps/thu-info-app/src/components/schedule/schedule.tsx
apps/thu-info-app/src/ui/schedule/schedule.tsx

So that it will not need ugly width calculation.
And it will not get to the next week's schedule.

fix: Altered schedule block sizing logic

---

apps/thu-info-app/babel.config.json
apps/thu-info-app/package.json

Switch to `@react-native/babel-preset`

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/ui/settings/feedback.tsx
packages/thu-info-lib/src/lib/app.ts

简单调整了一下 UI， 把二维码放大了一点， 然后使得二维码验证支持 http 格式

fix: Feedback QRCode UI & http scheme

---

apps/thu-info-app/src/ui/schedule/schedule.tsx

fix: Corrected 19:00-21:00 exam start time

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/ui/home/networkOnlineDevices.tsx
packages/thu-info-lib/src/lib/network.ts
packages/thu-info-lib/src/utils/srunCrypto.ts

Used btoa to simplify srun Base64
Closes #570

fix: Refactored xB64encode & proxy import bugfixes

---

apps/thu-info-app/src/components/Root.tsx

feat: Hide school calendar temporaily

---

apps/thu-info-app/src/ui/home/home.tsx

fix: Removed calendar entry

---

apps/thu-info-app/src/ui/home/dorm.tsx
apps/thu-info-app/src/ui/home/home.tsx

feat: Removed Dorm Electricity

---

apps/thu-info-app/src/components/Root.tsx
apps/thu-info-app/src/ui/home/home.tsx
apps/thu-info-app/src/ui/home/schoolCalendar.tsx
packages/thu-info-lib/src/constants/strings.ts
packages/thu-info-lib/src/index.ts
packages/thu-info-lib/src/lib/basics.ts

feat: New School Calendar

---

apps/thu-info-app/src/ui/home/bankPayment.tsx

feat: improve loading feedback in bank payment

---

apps/thu-info-app/src/ui/settings/feedback.tsx

adjust feedback's ui: align height of text input and submit button, add disabled visual effect to buttons, adjust title

feat: improve feedback ui

---

apps/thu-info-app/src/assets/colors/dark.ts
apps/thu-info-app/src/assets/colors/light.ts
apps/thu-info-app/src/assets/colors/pkuDark.ts
apps/thu-info-app/src/assets/colors/pkuLight.ts
apps/thu-info-app/src/components/schedule/schedule.tsx
apps/thu-info-app/src/ui/schedule/schedule.tsx

add a color to make the length of the list a prime, reduce padding when overflow, adjust seperate line color

fix: fix color and overflow problems of schedule

---

apps/thu-info-app/src/components/Root.tsx

#628 -> 1
increase bottom margin of bottom tab

feat: increase bottom margin

---

apps/thu-info-app/src/assets/icons/IconIncome.tsx

#628 -> 3
add a small purple band

feat: adjust income icon

---

apps/thu-info-app/src/components/settings/paginatedRefreshListScreen.tsx
apps/thu-info-app/src/ui/home/invoice.tsx

#628 -> 4
add round border to fapiao list

feat: add round border to fapiao list

---

apps/thu-info-app/src/components/settings/items.tsx
apps/thu-info-app/src/ui/settings/feedback.tsx
apps/thu-info-app/src/ui/settings/functionManagement.tsx
apps/thu-info-app/src/ui/settings/privacy.tsx
apps/thu-info-app/src/ui/settings/settings.tsx

#628 -> 5
fix separator and adjust some styles in settings page

fix: fix some ui stuff in settings page

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/redux/slices/config.ts
apps/thu-info-app/src/ui/schedule/schedule.tsx
apps/thu-info-app/src/ui/settings/scheduleSettings.tsx

#622 and #621 
make schedule UI revertable

feat: add schedule UI config

---

apps/thu-info-app/src/ui/home/home.tsx

#628 -> 2
remove home section content container's min height restriction
idk, test and help needed

feat: adjust home page styles

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/ui/schedule/scheduleDetail.tsx

#628 -> 6
Adjust button's style and improve choice help text for "once"

fix: adjust button's style and improve choice text for "once"

---

apps/thu-info-app/src/ui/home/dormScore.tsx

#628 
enhance DormScoreScreen with theme support

feat: enhance DormScoreScreen with theme support

---

apps/thu-info-app/src/ui/home/networkOnlineDevices.tsx

#628 
adjust border radius, adjust keyboard vertical offset

fix: some fix for online devices

---

apps/thu-info-app/src/components/settings/paginatedRefreshListScreen.tsx
apps/thu-info-app/src/components/settings/simpleRefreshListScreen.tsx
apps/thu-info-app/src/components/views.tsx
apps/thu-info-app/src/ui/home/bankPayment.tsx
apps/thu-info-app/src/ui/home/classroomDetail.tsx
apps/thu-info-app/src/ui/home/classroomList.tsx
apps/thu-info-app/src/ui/home/crCoursePlan.tsx
apps/thu-info-app/src/ui/home/crHome.tsx
apps/thu-info-app/src/ui/home/crSearchResult.tsx
apps/thu-info-app/src/ui/home/expenditure.tsx
apps/thu-info-app/src/ui/home/form.tsx
apps/thu-info-app/src/ui/home/libRoomSelect.tsx
apps/thu-info-app/src/ui/home/library.tsx
apps/thu-info-app/src/ui/home/networkDetail.tsx
apps/thu-info-app/src/ui/home/networkOnlineDevices.tsx
apps/thu-info-app/src/ui/home/report.tsx
apps/thu-info-app/src/ui/home/sportsDetail.tsx
apps/thu-info-app/src/ui/news/news.tsx
apps/thu-info-app/src/ui/news/newsFav.tsx
apps/thu-info-app/src/ui/schedule/schedule.tsx

#628 -> 10
add progress background color to refresh indicator

feat: refresh indicator support dark mode

---

apps/thu-info-app/src/components/views.tsx
apps/thu-info-app/src/ui/home/campusCard.tsx
apps/thu-info-app/src/ui/home/electricity.tsx
apps/thu-info-app/src/ui/home/expenditure.tsx
apps/thu-info-app/src/ui/home/form.tsx
apps/thu-info-app/src/ui/home/income.tsx
apps/thu-info-app/src/ui/home/invoice.tsx
apps/thu-info-app/src/ui/home/libRoomSelect.tsx
apps/thu-info-app/src/ui/home/library.tsx
apps/thu-info-app/src/ui/home/networkDetail.tsx
apps/thu-info-app/src/ui/home/report.tsx
apps/thu-info-app/src/ui/home/sports.tsx
apps/thu-info-app/src/ui/home/sportsDetail.tsx
apps/thu-info-app/src/ui/home/sportsSelect.tsx
apps/thu-info-app/src/ui/home/water.tsx

fix: fix all separators

---

apps/thu-info-app/src/ui/home/home.tsx

centered hint in recent functions

fix: fix text not centered in recent functions

---

apps/thu-info-app/src/ui/settings/settings.tsx

#627 
display buttons according to login status

fix: fix login buttons in settings page

---

apps/thu-info-app/src/ui/schedule/schedule.tsx
packages/thu-info-lib/src/models/schedule/schedule.ts

fix: fix wrong time in hide schedule

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/ui/home/campusCard.tsx

#666 
only update recharge amount when recharge is successful

fix: only update recharge amount when succeed

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/redux/store.ts
packages/thu-info-lib/src/index.ts
packages/thu-info-lib/src/lib/core.ts

Added an Alert to redirect users to id.t.e.c in order to manage 2FA trusted devices
Added device name to 2FA trusted device description

2FA-related optimizations

---

apps/thu-info-app/src/assets/translations/en.ts
apps/thu-info-app/src/assets/translations/zh.ts
apps/thu-info-app/src/ui/home/deepseek.tsx

1. Improve generate title prompt
2. Add animation
3. Fix searching status display
no
Notice: a refactor of this code is in progress, but I don’t expect it to be ready soon, so I’ve submitted this PR first. The refactor might need to be deferred to the next iteration.

feat: improve deepseek screen

---

apps/thu-info-app/src/utils/i18n.ts

fix: use === to check if a translation key is missing
